import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import pickle
import EDA as eda
import AalenAdditiveModel as AAM

#Pickle the list of bootstrap_number models.
filename1 = 'kac3_google_user_date.csv'
filename2 = 'kac3_google_history.csv'
filename3 = 'kac3_google_user_filter.csv'

# build the clean data set and save it in cleaned_dataset.p
cleaned_dataset_km = eda.clean_data_km(filename1, filename2, filename3)
filename = 'cleaned_dataset_km.p'
fileobject = open(filename, 'wb')
user_dataset_km= pickle.dump(cleaned_dataset_km, fileobject)
fileobject.close()

# load the cleaned data set in the previous step.
filename = 'cleaned_dataset_km.p'
fileobject = open(filename, 'rb')
user_dataset_km= pickle.load(fileobject)
fileobject.close()

eda.plot_Kaplan_Meier_overall(user_dataset_km)
eda.plot_Kaplan_Meier_feature(user_dataset_km)

'''This program imports the nonprofit data set and uses only the uncensored
data to train 100 bootstrap models.  Each model was generated by randomly
drawing data with replacement from the original uncensored data set.

Note that the results in "Readme.MD" were generated with 10 000 bootstrap models.
However, the resultant pickled file for the list of models would have been too large
to store on github (>8 GB), so only 100 bootstrap models were generated here as
an example.

The data set was loaded from a pickled file called 'cleaned_dataset.p.'

The list of bootstrap models are pickled as 'AAF_100.p'.

'''
# build the clean data set and save it in cleaned_dataset.p
cleaned_dataset = eda.clean_data(filename1, filename2, filename3)
filename = 'cleaned_dataset.p'
fileobject = open(filename, 'wb')
user_dataset= pickle.dump(cleaned_dataset, fileobject)
fileobject.close()

# load the cleaned data set in the previous step.
filename = 'cleaned_dataset.p'
fileobject = open(filename, 'rb')
user_dataset= pickle.load(fileobject)
fileobject.close()
#Call Bootstrap function to perform bootstrap modelling
#Number of bootstrap models = 100
bootstrap_number = 100
AAF_100 = AAM.Bootstrap(user_dataset, bootstrap_number)

#Pickle the list of bootstrap_number models.
filename = 'AAF_100.p'
fileobject = open(filename, 'wb')
user_dataset= pickle.dump(AAF_100, fileobject)
fileobject.close()

'''This program loads a pickled user data set and a list of n bootstrap trained models.  Then it passes
the list of models and the censored part of the data set to the Aalen_predict_lifetimes functions, which
generates a mean and median predicted lifetimes for each censored user.  The mean and median lifetimes
are combined with the data set as new columns and output as a csv file.
'''
#Load the pickled user dataset
print 'Loading cleaned dataset...'
filename = 'cleaned_dataset.p'
fileobject = open(filename, 'rb')
user_dataset= pickle.load(fileobject)
fileobject.close()
print 'Cleaned dataset loaded.'


#Select only the censored data to make predictions of.  These are users who have not churned.  Note the model was trained on uncensored (churned) users because they are the ones whose lifetimes are known.

censored_user_dataset = user_dataset[user_dataset['censored'] == 1]

#Load the pickled list of Aalen models.
print 'Loading list of bootstrap trained models...'
filename = 'AAF_100.p'
fileobject = open(filename, 'rb')
AAF_100 = pickle.load(fileobject)
fileobject.close()
print 'bootstrap trained models loaded.'


#This calls the Aalen_predict_lifetimes function which uses the bootstrap models to predict
#the lifetimes of each line of data.  The mean and median lifetimes of each user is added to
#as new columns to the dataframe and then returned.
print 'Calling Aalen_predicting_lifetimes to make predictions for lifetimes...'
df_lifetime = AAM.Aalen_predict_lifetimes(AAF_100, censored_user_dataset)
print 'Predictions completed'

df_lifetime.to_csv('dataset_with_predicted_lifetimes.csv')

print 'DATA SET WITH PREDICTED LIFETIME COLUMNS HAS BEEN SAVED TO THIS FOLDER AS csv FILE.'

'''This program loads a list of trained bootstrap model, calculate their cumulative hazard functions, and plot them.
Each figure represents n bootstrap models of a hazard.  The spread of the function nicely illustrates the variance
between the functions.
'''

#Pass the list to the following function to be plotted.
AAM.plot_cum_haz_functions(AAF_list_100, 10)

'''This program invokes the plot_user_cum_haz function from Aalen_KMF_plots.py to
plot the cumulative hazard functions for a random number of chosen users.  NB: This is
the hazard function individually customized for each user, depending on her/his features.
'''

#This is the number of random censored users whose cumulative hazard function is to be plotted.
number_users_to_be_plotted = 2
#These are the parameters for the figures.
years = 5
y_max = 3
lw = 0.03
#Call the function to plot the users' cumulative hazard function.
AAM.plot_user_cum_haz(AAF_list_100, user_dataset, number_users_to_be_plotted, years, y_max, lw)
